#!/usr/bin/env python3
"""Ensure gemini-cli / agy load the target project's AGENTS.md, and that
.gemini/GEMINI.md is a thin pointer to it rather than a drifting copy.

gemini-cli reads only GEMINI.md by default — so the roster and graph-DAG blocks
ed-orchestrate-init splices into AGENTS.md are invisible to a Gemini-family
harness unless `.gemini/settings.json` names AGENTS.md as a context file. This
merges `context.fileName` to include both AGENTS.md and GEMINI.md (preserving
every other key, e.g. mcpServers), and splices a small idempotent pointer block
into `.gemini/GEMINI.md` (creating it if missing; never touching content outside
its markers). A project that kept a duplicated copy of its AGENTS.md
conventions in GEMINI.md keeps it — the summary tells the user it can now go.

Usage: ensure_gemini_context.py [--gemini-dir .gemini] [--agents-md AGENTS.md]
"""
import argparse
import json
import os
import re
import sys

BEGIN = "<!-- BEGIN:ed-orchestrate-gemini-pointer -->"
END = "<!-- END:ed-orchestrate-gemini-pointer -->"
SPLICE_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
WANTED = ["AGENTS.md", "GEMINI.md"]


def render_block(agents_rel):
    return f"""{BEGIN}
<!-- Generated by ed-orchestrate-init — do not hand-edit between these markers;
     re-run ed-orchestrate-init instead. -->

Read **[AGENTS.md]({agents_rel})** — it is this project's single source of truth for
conventions, the shared task-memory protocol, the orchestrator workflow, and the
sub-agent roster. `.gemini/settings.json` loads it as a context file, so gemini-cli
sees it alongside this file. Don't duplicate its content here; this file only adds
Gemini/agy-specific notes. If anything here conflicts with AGENTS.md, AGENTS.md wins.

## Are you the orchestrator right now?

AGENTS.md's orchestrator workflow applies only when you are this session's main /
coordinating harness — the one the human is talking to directly, started without a
scoped role. If you were dispatched with a scoped role — you received
"Execute [[TASK-xxx]]…", a task-node or ITER-ledger pointer, or a prompt naming your
role — you are **not** the orchestrator. Follow your role's `systemPromptSeed` in
`.orchestrate/agents.json` (agy has no per-project agent files, so the dispatch
prompt and that seed are your role definition) and AGENTS.md's worker rules.

## agy / Gemini headless notes

- **Unattended**: run to completion without pausing for confirmations or interactive
  questions. If blocked, write the question into the task node and stop. Read enough
  to judge, then write the verdict — a review that never concludes is worse than a
  short one.
- **Cold-start budget**: read your task node, its `governed_by` ADRs, the core gotchas
  file, and ONLY the files in the node's `context:` frontmatter.
- **File access**: headless runs only see directories passed with `--add-dir` (plus
  trusted workspaces). Keep inputs/outputs inside the repo, not `/tmp`.
- **Command shape**: headless agy matches each command's FIRST word against
  `permissions.allow` in `~/.gemini/antigravity-cli/settings.json` and silently denies
  anything else. Start every command with an allow-listed program; never prefix env
  vars (`FOO=1 npx …`), avoid `cd … &&`, pipes, brace expansion and compound
  one-liners. Prefer `npm run` scripts and single commands.
{END}
"""


def splice(existing, block):
    if BEGIN in existing and END in existing:
        return SPLICE_RE.subn(lambda _m: block.rstrip("\n"), existing, count=1)[0]
    if not existing.strip():
        return block
    # Pointer goes FIRST so it frames whatever older content follows.
    return block + "\n" + existing


def ensure_settings(path):
    data = {}
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            raw = f.read()
        if raw.strip():
            try:
                data = json.loads(raw)
            except json.JSONDecodeError as e:
                print(f"ERROR: {path} is not valid JSON ({e}); add "
                      f'"context": {{"fileName": {json.dumps(WANTED)}}} by hand.', file=sys.stderr)
                return "error"
    if not isinstance(data, dict):
        print(f"ERROR: {path} is not a JSON object; leaving it alone.", file=sys.stderr)
        return "error"
    ctx = data.setdefault("context", {})
    if not isinstance(ctx, dict):
        print(f"ERROR: {path} `context` is not an object; leaving it alone.", file=sys.stderr)
        return "error"
    current = ctx.get("fileName", [])
    if isinstance(current, str):
        current = [current]
    # gemini-cli's default is GEMINI.md; keep it when adding AGENTS.md.
    merged = list(current) or []
    for name in WANTED:
        if name not in merged:
            merged.append(name)
    if merged == ctx.get("fileName"):
        return "already"
    existed = os.path.exists(path)
    ctx["fileName"] = merged
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
        f.write("\n")
    return "updated" if existed else "created"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--gemini-dir", default=".gemini")
    parser.add_argument("--agents-md", default="AGENTS.md")
    args = parser.parse_args()

    settings = os.path.join(args.gemini_dir, "settings.json")
    result = ensure_settings(settings)
    if result == "error":
        sys.exit(1)
    print(f"{settings}: {'already loads AGENTS.md' if result == 'already' else result}")

    gemini_md = os.path.join(args.gemini_dir, "GEMINI.md")
    agents_rel = os.path.relpath(args.agents_md, args.gemini_dir)
    try:
        with open(gemini_md, "r", encoding="utf-8") as f:
            existing = f.read()
    except FileNotFoundError:
        existing = ""
    new = splice(existing, render_block(agents_rel))
    if new == existing:
        print(f"{gemini_md}: pointer already current")
        return
    with open(gemini_md, "w", encoding="utf-8") as f:
        f.write(new)
    outside = SPLICE_RE.sub("", new).strip()
    print(f"{gemini_md}: {'pointer updated' if BEGIN in existing else 'pointer added'}")
    if outside:
        print(
            f"NOTE: {gemini_md} has content outside the pointer block. If it duplicates "
            "AGENTS.md (a common pre-pointer pattern), it can now be deleted — gemini-cli "
            "loads AGENTS.md directly.",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
