#!/usr/bin/env python3
"""Ensure a target project's CLAUDE.md imports AGENTS.md.

Claude Code auto-loads AGENTS.md at session start ONLY when no CLAUDE.md
exists anywhere on the path from the working directory up
(https://code.claude.com/docs/en/memory.md#when-claude-code-reads-agents-md).
Any project with its own CLAUDE.md — which is common, and which
ed-orchestrate-init never controls — silently shadows AGENTS.md, so the
roster and graph-DAG blocks spliced there are never read unless someone
manually points Claude at them. `@path` imports inside CLAUDE.md are the
one thing Claude Code always resolves regardless of that shadowing, so this
splices a small idempotent block containing `@AGENTS.md` into CLAUDE.md
(creating it if missing) — never touches any other content in the file.

Usage: ensure_claude_md_import.py <CLAUDE.md path> [--import-path AGENTS.md]
"""
import argparse
import os
import re

BEGIN = "<!-- BEGIN:ed-orchestrate-claude-import -->"
END = "<!-- END:ed-orchestrate-claude-import -->"
SPLICE_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)


def render_block(import_path):
    return (
        f"{BEGIN}\n"
        "<!-- Generated by ed-orchestrate-init. Claude Code only auto-loads AGENTS.md\n"
        "     when no CLAUDE.md exists on the path — since this file exists, that\n"
        "     never happens on its own, so this import forces it every session.\n"
        "     Do not hand-edit between these markers; re-run ed-orchestrate-init\n"
        "     instead. -->\n\n"
        f"@{import_path}\n"
        f"{END}\n"
    )


def splice(existing_content, block):
    if BEGIN in existing_content and END in existing_content:
        new_content, _ = SPLICE_RE.subn(block.rstrip("\n"), existing_content, count=1)
        return new_content
    if not existing_content.strip():
        return block
    if existing_content.endswith("\n"):
        return existing_content + "\n" + block
    return existing_content + "\n\n" + block


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("claude_md")
    parser.add_argument("--import-path", default="AGENTS.md")
    args = parser.parse_args()

    try:
        with open(args.claude_md, "r", encoding="utf-8") as f:
            existing = f.read()
    except FileNotFoundError:
        existing = ""

    already_wired = BEGIN in existing
    new_content = splice(existing, render_block(args.import_path))

    if new_content == existing:
        print(f"Already imports {args.import_path}: {args.claude_md}")
        return

    with open(args.claude_md, "w", encoding="utf-8") as f:
        f.write(new_content)
    print(
        f"{'Updated' if already_wired else 'Added'} @{args.import_path} import in "
        f"{args.claude_md}"
    )


if __name__ == "__main__":
    main()
