#!/usr/bin/env python3
"""Render the ed-orchestrate roster block from agents.json, and optionally splice
it idempotently into a target AGENTS.md.

Usage:
  render_agents_md_block.py <agents.json> [--project-name NAME]
      Print the rendered block (with markers) to stdout. Pure, no writes.

  render_agents_md_block.py <agents.json> --splice <AGENTS.md path>
      Render the block and splice it into the given AGENTS.md in place:
      replace the existing <!-- BEGIN:ed-orchestrate-roster --> ... <!-- END -->
      span if found, else append at EOF (creating the file if missing). Content
      outside the marker span is never touched.
"""
import argparse
import datetime
import json
import re
import sys

AGENTS_MD_WARN_BYTES = 30000  # Codex reads at most project_doc_max_bytes (32768) of AGENTS.md
BEGIN = "<!-- BEGIN:ed-orchestrate-roster -->"
END = "<!-- END:ed-orchestrate-roster -->"
SPLICE_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)


def render_block(data):
    today = datetime.date.today().isoformat()
    roles = data.get("roles", {})
    default_role = (data.get("defaults") or {}).get("role", "")

    lines = []
    lines.append(BEGIN)
    lines.append(
        "<!-- Generated by ed-orchestrate-init from .orchestrate/agents.json — do not\n"
        "     hand-edit between these markers; re-run ed-orchestrate-init instead.\n"
        f"     Last generated: {today}. -->"
    )
    lines.append("")
    lines.append("## Sub-agent roster (ed-orchestrate)")
    lines.append("")
    lines.append(
        "This project delegates coding sub-tasks to configured sub-agents via the "
        "`ed-orchestrate` skill (Claude Code) — the same roster is honored by opencode "
        "and Antigravity/agy through this file. Full machine-readable config: "
        "`.orchestrate/agents.json`."
    )
    lines.append("")
    lines.append("| Role | Harness | Model | Provider | Effort | Default mode | Fallbacks |")
    lines.append("|---|---|---|---|---|---|---|")
    for name, role in roles.items():
        provider = role.get("provider") or "—"
        effort = role.get("effort") or "—"
        fallbacks = ", ".join(
            f"{fb.get('harness') or role.get('harness', '—')} ({fb.get('model', '—')})"
            for fb in (role.get("fallbacks") or [])
        ) or "—"
        lines.append(
            f"| {name} | {role.get('harness', '—')} | {role.get('model', '—')} | "
            f"{provider} | {effort} | {role.get('delegationMode', '—')} | {fallbacks} |"
        )
    lines.append("")
    if default_role:
        lines.append(f"Default role when unspecified: **{default_role}**.")
        lines.append("")
    lines.append(
        'To delegate: ask for "hand off <task> to <role>" (fire-and-forget) or '
        '"supervise <role> on <task>" (blocking/monitored). To change this roster, '
        "run `ed-orchestrate-init` again."
    )
    lines.append(END)
    return "\n".join(lines) + "\n"


def splice(existing_content, block):
    if BEGIN in existing_content and END in existing_content:
        new_content, count = SPLICE_RE.subn(block.rstrip("\n"), existing_content, count=1)
        return new_content
    if not existing_content.strip():
        return block
    if existing_content.endswith("\n"):
        return existing_content + "\n" + block
    return existing_content + "\n\n" + block


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("agents_json")
    parser.add_argument("--project-name")
    parser.add_argument("--splice", metavar="AGENTS_MD_PATH")
    args = parser.parse_args()

    try:
        with open(args.agents_json, "r", encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        print(f"{args.agents_json}: failed to read/parse JSON: {e}", file=sys.stderr)
        sys.exit(1)

    block = render_block(data)

    if not args.splice:
        print(block, end="")
        return

    try:
        with open(args.splice, "r", encoding="utf-8") as f:
            existing = f.read()
    except FileNotFoundError:
        existing = ""

    new_content = splice(existing, block)

    with open(args.splice, "w", encoding="utf-8") as f:
        f.write(new_content)

    if len(new_content.encode("utf-8")) > AGENTS_MD_WARN_BYTES:
        print(
            f"WARN: {args.splice} is {len(new_content.encode('utf-8'))} bytes; Codex may ignore everything past "
            "project_doc_max_bytes (default 32 KiB) — trim it or raise that setting "
            "in ~/.codex/config.toml",
            file=sys.stderr,
        )
    print(f"Spliced ed-orchestrate-roster block into {args.splice}")


if __name__ == "__main__":
    main()
