#!/usr/bin/env python3
"""Wire up the optional graph-engineered task-DAG pattern in a target project:
creates the shared task-memory directory + task-node template, splices a
usage block into AGENTS.md, gitignores the memory directory (it's
local-machine scratch, not committed), and registers it as an Orca
worktree-shared directory in orca.yaml if that file exists or is requested.

Usage:
  setup_graph_dag.py <memory-dir> [--agents-md AGENTS.md] [--gitignore .gitignore]
      [--orca-yaml orca.yaml] [--no-orca-yaml]

Idempotent: safe to re-run. Never overwrites an existing TASK-template.md,
never duplicates a gitignore line, never duplicates an AGENTS.md block or an
orca.yaml sharedDirectories entry.
"""
import argparse
import datetime
import os
import re
import sys

BEGIN = "<!-- BEGIN:ed-orchestrate-graph-dag -->"
END = "<!-- END:ed-orchestrate-graph-dag -->"
SPLICE_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)

TASK_TEMPLATE = """---
id: TASK-000
title: Task Template
status: backlog # backlog | ready | in-progress | review | done
assigned_to: coder # any role name in this project's .orchestrate/agents.json
depends_on: []
blocks: []
governed_by: []
tags: [task, dag]
date_created: {date}
---

## Scope Fence

- **Allowed target files**: list the files/dirs this task may touch.
- **Forbidden zones**: everything else. If the task needs more, stop and log
  a candidate follow-up task instead of widening scope here.

## Execution & Diffs Log
*(sub-agent populates this section upon completing work)*

- **Status Change**: `in-progress` -> `review`
- **Files Modified**:
- **Summary of Changes**:
- **Verification Evidence**:
- **New Gotchas Discovered**:
"""


def render_agents_md_block(memory_dir):
    today = datetime.date.today().isoformat()
    tasks_dir = f"{memory_dir.rstrip('/')}/tasks/"
    lines = [
        BEGIN,
        (
            "<!-- Generated by ed-orchestrate-init — do not hand-edit between these\n"
            "     markers; re-run ed-orchestrate-init instead.\n"
            f"     Last generated: {today}. -->"
        ),
        "",
        "## Graph-engineered task delegation (ed-orchestrate)",
        "",
        (
            f"This project tracks multi-step work as a task DAG under `{tasks_dir}` "
            "instead of a flat delegation loop — see "
            "`ed-orchestrate/references/graph-dag.md` for the full pattern."
        ),
        "",
        (
            f"- The orchestrator delegates to `planner` to produce task-node files in "
            f"`{tasks_dir}` (template: `{tasks_dir}TASK-template.md`)."
        ),
        (
            "- Each task node's frontmatter (`depends_on`, `blocks`, `assigned_to`) "
            "is the graph — the orchestrator dispatches every `ready` node, not a "
            "fixed sequence."
        ),
        (
            "- Dispatch sub-agents with a task-node pointer "
            '("Execute [[TASK-NNN]].") — the sub-agent reads its own node and linked '
            "context, not a re-explained brief."
        ),
        (
            "- `integrator` merges parallel task branches and runs the full suite "
            "once per batch; `curator` periodically folds finished task reports "
            "into shared knowledge notes and prunes stale ones."
        ),
        f"- `{memory_dir.rstrip('/')}/` is local-machine scratch — gitignored, not committed.",
        END,
    ]
    return "\n".join(lines) + "\n"


def splice(existing_content, block):
    if BEGIN in existing_content and END in existing_content:
        new_content, _ = SPLICE_RE.subn(block.rstrip("\n"), existing_content, count=1)
        return new_content
    if not existing_content.strip():
        return block
    if existing_content.endswith("\n"):
        return existing_content + "\n" + block
    return existing_content + "\n\n" + block


def ensure_tasks_dir_and_template(memory_dir):
    tasks_dir = os.path.join(memory_dir, "tasks")
    os.makedirs(tasks_dir, exist_ok=True)
    template_path = os.path.join(tasks_dir, "TASK-template.md")
    if not os.path.exists(template_path):
        with open(template_path, "w", encoding="utf-8") as f:
            f.write(TASK_TEMPLATE.format(date=datetime.date.today().isoformat()))
        return template_path, True
    return template_path, False


def ensure_gitignore(gitignore_path, memory_dir):
    ignore_line = f"{memory_dir.rstrip('/')}/"
    existing = ""
    if os.path.exists(gitignore_path):
        with open(gitignore_path, "r", encoding="utf-8") as f:
            existing = f.read()
    if any(line.strip() == ignore_line for line in existing.splitlines()):
        return False
    addition = ("" if existing.endswith("\n") or not existing else "\n") + (
        "\n" if existing.strip() else ""
    ) + f"# ed-orchestrate graph-DAG shared task memory (local-machine only)\n{ignore_line}\n"
    with open(gitignore_path, "w", encoding="utf-8") as f:
        f.write(existing + addition)
    return True


SHARED_DIRS_RE = re.compile(r"(sharedDirectories:\s*\n(?:\s*-\s*.+\n)*)", re.MULTILINE)


def ensure_orca_yaml(orca_yaml_path, memory_dir):
    """Best-effort, regex-based (no YAML dependency) idempotent insert into an
    existing `sharedDirectories:` list, or a minimal new file if none exists.
    Never rewrites unrelated content; on any ambiguity, does nothing and
    returns a message telling the caller to add the line by hand."""
    entry = memory_dir.rstrip("/")
    if not os.path.exists(orca_yaml_path):
        content = (
            "# Orca workspace configuration — directories symlinked into every\n"
            "# Orca-created worktree so they see the same state as the main checkout.\n"
            "worktree:\n"
            "  sharedDirectories:\n"
            "    - node_modules\n"
            "    - .orchestrate\n"
            f"    - {entry}\n"
        )
        with open(orca_yaml_path, "w", encoding="utf-8") as f:
            f.write(content)
        return "created"

    with open(orca_yaml_path, "r", encoding="utf-8") as f:
        content = f.read()

    if re.search(rf"^\s*-\s*{re.escape(entry)}\s*$", content, re.MULTILINE):
        return "already-present"

    match = SHARED_DIRS_RE.search(content)
    if not match:
        return "manual"

    block = match.group(1)
    # Match the indent of the list items already there.
    item_match = re.search(r"^(\s*)-\s*", block, re.MULTILINE)
    indent = item_match.group(1) if item_match else "    "
    new_block = block.rstrip("\n") + f"\n{indent}- {entry}\n"
    content = content[: match.start(1)] + new_block + content[match.end(1) :]
    with open(orca_yaml_path, "w", encoding="utf-8") as f:
        f.write(content)
    return "appended"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("memory_dir")
    parser.add_argument("--agents-md", default="AGENTS.md")
    parser.add_argument("--gitignore", default=".gitignore")
    parser.add_argument("--orca-yaml", default="orca.yaml")
    parser.add_argument("--no-orca-yaml", action="store_true")
    args = parser.parse_args()

    template_path, created = ensure_tasks_dir_and_template(args.memory_dir)
    print(f"{'Created' if created else 'Already exists'}: {template_path}")

    try:
        with open(args.agents_md, "r", encoding="utf-8") as f:
            existing = f.read()
    except FileNotFoundError:
        existing = ""
    new_content = splice(existing, render_agents_md_block(args.memory_dir))
    with open(args.agents_md, "w", encoding="utf-8") as f:
        f.write(new_content)
    print(f"Spliced ed-orchestrate-graph-dag block into {args.agents_md}")

    changed = ensure_gitignore(args.gitignore, args.memory_dir)
    print(f"{'Updated' if changed else 'Already ignored'}: {args.gitignore}")

    if not args.no_orca_yaml:
        result = ensure_orca_yaml(args.orca_yaml, args.memory_dir)
        if result == "manual":
            print(
                f"WARN: could not confidently locate sharedDirectories in {args.orca_yaml}; "
                f"add `- {args.memory_dir.rstrip('/')}` under worktree.sharedDirectories by hand.",
                file=sys.stderr,
            )
        else:
            print(f"orca.yaml: {result}")


if __name__ == "__main__":
    main()
